### ISSUE TITLE
홈피드 리팩토링

### ISSUE THREAD

**Issue by chohe3212** [FRONTENDSCHOOL7/final-09-campfeed#137]
## 📑 Description

홈피드 리팩토링

## 📝 Todo

- [ ]  6번째줄 안쓰는거 지우기
- [ ]  예약detail 모달 웹 버전에서도 가운데뜨게하
- [ ]  모달뜨는 코드를 예약 컴포넌트로 옮기기 → api도 지우고 item 으로 모달띄우게하
- [ ]  홈피드 안에있는 postitem파일 지우기. (진짜 안쓰이는지 다시 확인.)
- [ ]  PostList에 있는 스타일 → post.style.jsx 에 넣기.
- [ ]  여러개 이미지 끝까지 넘겼을때 다음 버튼 비활성화되게.
- [ ]  PostItem → 148번째줄 PostMap 굳이 밖으로 뺄 이유가 잇나?
- [ ]  토스트 컴포넌트에 *if* (deleteMsg) console.log(deleteMsg); 삭제해도될듯

## 📍 ETC

기타사항
