### ISSUE TITLE
로그인 페이지 리팩토링

### ISSUE THREAD

**Issue by donguramee** [FRONTENDSCHOOL7/final-09-campfeed#141]
## 📑 Description

설명을 작성해주세요.

## 📝 Todo

- [ ]  이메일 잘못 입력할때 잘못된 이메일 형식입니다 표시해주기
- [ ]  체험해보기 만들기
- [ ]  loginEmail 23 번째줄 emailPattern
    
    ```jsx
    const emailPattern = /^[A-Za-z0-9_\.\-]+@[A-Za-z0-9\-]+\.[A-Za-z0-9\-]+/;
    // 밑에꺼로 바꾸기 (오류는 문자 집합(character set) 내에서 하이픈(-) 기호 앞에 불필요한 백슬래시()가 사용되었기 때문)
    const emailPattern = /^[A-Za-z0-9_.-]+@[A-Za-z0-9-]+\.[A-Za-z0-9-]+/;
    ```
    
- [ ]  api 데이터를 정제 하고 넘겨야함.
- [ ]  콘솔 지우기
- [ ]  onSubmit → form태그로 옮기기

## 📍 ETC

기타사항
