### ISSUE TITLE
회원가입 리팩토링

### ISSUE THREAD

**Issue by sojinkorea** [FRONTENDSCHOOL7/final-09-campfeed#145]
## 📑 Description

회원가입 페이지 리팩토링

## 📝 Todo

- [ ] 이메일 토글로 보여주기
- [ ] 이메일 유효성 검사 수정
- [ ] 비밀번호 확인 추가
