### ISSUE TITLE
상품 예약 상세페이지 모달창 구현

### ISSUE THREAD

**Issue by gunhee98** [FRONTENDSCHOOL7/final-09-campfeed#55]
## 📑 Description

상품 예약페이지에서 상품을 눌렀을때 들어가지는 페이지 구현

## 📝 Todo

- [ ] 모달 스타일 제작
- [ ] 상품api로 데이터 가져오기
- [ ] 데이터 화면에 렌더링 시키기

## 📍 ETC

기타사항
